export const GAME_EXTS = new Set(["gb","gbc","gba","nds","n64","z64","v64","sfc","smc","nes","gg","sms","md","gen","pce","nsp","xci","cia","3ds","rom"]);

export const EXT_DESCRIPTIONS: Record<string, string> = {
  gb:   "Game Boy ROM — Nintendo Game Boy (1989)",
  gbc:  "Game Boy Color ROM — Nintendo Game Boy Color (1998)",
  gba:  "Game Boy Advance ROM — Nintendo GBA (2001)",
  nds:  "Nintendo DS ROM — Nintendo DS (2004)",
  n64:  "Nintendo 64 ROM (big-endian)",
  z64:  "Nintendo 64 ROM (big-endian, .z64 format)",
  v64:  "Nintendo 64 ROM (byte-swapped)",
  sfc:  "Super Nintendo ROM — SNES (1990)",
  smc:  "Super Nintendo ROM — SNES (SMC format)",
  nes:  "Nintendo Entertainment System ROM (1983)",
  gg:   "Sega Game Gear ROM (1990)",
  sms:  "Sega Master System ROM (1985)",
  md:   "Sega Mega Drive / Genesis ROM (1988)",
  gen:  "Sega Genesis ROM (1989)",
  pce:  "PC Engine / TurboGrafx-16 ROM (1987)",
  nsp:  "Nintendo Switch Package — eShop game",
  xci:  "Nintendo Switch Cartridge Image",
  cia:  "Nintendo 3DS Installable Archive",
  "3ds":"Nintendo 3DS ROM",
  rom:  "Generic ROM image",
  pdf:  "Portable Document Format — Adobe PDF",
  zip:  "ZIP archive — compressed folder",
  rar:  "RAR archive — compressed folder",
  "7z":"7-Zip archive — high compression",
  tar:  "TAR archive — Unix tape format",
  gz:   "Gzip compressed file",
  doc:  "Microsoft Word 97–2003 document",
  docx: "Microsoft Word document (Office Open XML)",
  xls:  "Microsoft Excel 97–2003 spreadsheet",
  xlsx: "Microsoft Excel spreadsheet (Office Open XML)",
  ppt:  "Microsoft PowerPoint 97–2003 presentation",
  pptx: "Microsoft PowerPoint presentation",
  txt:  "Plain text file",
  csv:  "Comma-separated values spreadsheet",
  json: "JSON data file",
  xml:  "XML data/markup file",
  vcf:  "vCard contact file",
  apk:  "Android application package",
  exe:  "Windows executable",
  dmg:  "macOS disk image",
  iso:  "Optical disc image (ISO 9660)",
  mp3:  "MP3 audio file",
  wav:  "Waveform audio file",
  mp4:  "MPEG-4 video file",
  svg:  "Scalable Vector Graphics image",
  flv:  "Flash Video file",
  wmv:  "Windows Media Video",
  wma:  "Windows Media Audio",
  mid:  "MIDI music file",
  midi: "MIDI music file",
  epub: "Electronic publication — ebook format",
  pages:   "Apple Pages document",
  numbers: "Apple Numbers spreadsheet",
  key:     "Apple Keynote presentation",
  odt:  "OpenDocument Text — LibreOffice Writer",
  ods:  "OpenDocument Spreadsheet — LibreOffice Calc",
  odp:  "OpenDocument Presentation — LibreOffice Impress",
  rtf:  "Rich Text Format document",
  ics:  "iCalendar event / calendar invite",
  html: "HyperText Markup Language web page",
  htm:  "HyperText Markup Language web page",
  yaml: "YAML configuration / data file",
  yml:  "YAML configuration / data file",
  toml: "TOML configuration file",
  sql:  "SQL database script",
  cab:  "Windows Cabinet archive",
  xz:   "XZ compressed archive",
  bz2:  "Bzip2 compressed file",
  zst:  "Zstandard compressed file",
};
